name: Warehouse Data Collector

on:
  schedule:
    - cron: '0 8 * * *'  # 3 AM hora Colombia (UTC-5)
  workflow_dispatch:

env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  collect-data:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        #python -m pip install --upgrade pip
        pip install pandas requests pyarrow

    - name: Run data collector
      run: python api_collector.py

    - name: Verify generated files
      run: |
        echo "=== ARCHIVOS GENERADOS ==="
        ls -lh data/
        echo "=== TAMAÑO TOTAL ==="
        du -sh data/
        echo "=== RESUMEN ==="
        python -c "import pandas as pd; [print(f'{f.split(\"_\")[0]}: {len(pd.read_parquet(f\"data/{f}\"))} registros') for f in pd.Series(['sales_orders_1145.parquet', 'goods_receipts_1145.parquet', 'goods_issues_1145.parquet', 'inbound_deliveries_1145.parquet', 'outbound_deliveries_1145.parquet'])]"

    - name: Commit and push data
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git diff --quiet && git diff --staged --quiet || 
          (git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" && git push)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: warehouse-data
        path: data/*.parquet
        retention-days: 5
